(ns prezo.slide-zoom
  "Workshop owns workbench zoom — update `window.zoomLevel` and write `slide-zoom.css`.
   Keybindings call `zoom-in!+` / `zoom-out!+` / `zoom-reset!+`.
   Activate calls `sync!+` once."
  (:require ["vscode" :as vscode]
            ["fs" :as fs]
            ["path" :as path]
            [joyride.core :as joyride]))

(defonce !zoom-level (atom (or (.get (vscode/workspace.getConfiguration "window") "zoomLevel") 0)))

(defn- log! [& xs]
  (let [msg (str "slide-zoom: " (apply str xs))]
    (println msg)
    (.appendLine (joyride/output-channel) msg)))

(defn- workshop-root-uri
  []
  (if-let [folders (.-workspaceFolders vscode/workspace)]
    (.-uri (aget folders 0))
    (vscode/Uri.parse ".")))

(defn- factor-for [level]
  (+ 1 (/ level 4)))

(defn- slide-zoom-path
  []
  (path/join (.-fsPath (workshop-root-uri)) "slide-zoom.css"))

(defn- write-factor!
  [factor level]
  (let [css (str "/* Generated by prezo.slide-zoom — do not edit by hand */\n"
                 ":root {\n"
                 "  --window-zoom-factor: " factor ";\n"
                 "}\n")
        file (slide-zoom-path)]
    (fs/writeFileSync file css "utf-8")
    (log! "wrote factor=" factor " level=" level " → " file)
    factor))

(defn- set-level!+
  [level]
  (let [rounded (js/Math.round level)]
    (write-factor! (factor-for rounded) rounded)))

(defn sync!+
  []
  (let [level @!zoom-level
        factor (factor-for level)]
    (write-factor! factor level)))

(defn ^:export zoom-in!+
  []
  (vscode/commands.executeCommand "workbench.action.zoomIn")
  (set-level!+ (swap! !zoom-level inc))
  :ok)

(defn ^:export zoom-out!+
  []
  (vscode/commands.executeCommand "workbench.action.zoomOut")
  (set-level!+ (swap! !zoom-level dec))
  :ok)

(defn ^:export zoom-reset!+
  []
  (vscode/commands.executeCommand "workbench.action.zoomReset")
  (set-level!+ (reset! !zoom-level 0))
  :ok)
